using Coursework.Application.DTOs.PurchaseInvoices;
using Coursework.Application.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Coursework.Infrastructure.Services;

public class InvoicePdfService : IInvoicePdfService
{
    public InvoicePdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GeneratePurchaseInvoicePdf(PurchaseInvoiceDetailDto invoice)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(text => text.FontSize(10));

                page.Header().Element(header => ComposeHeader(header, invoice));

                page.Content().Element(content => ComposeContent(content, invoice));

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        }).GeneratePdf();
    }

    private static void ComposeHeader(IContainer container, PurchaseInvoiceDetailDto invoice)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(left =>
                {
                    left.Item().Text("AutoCare IMS")
                        .FontSize(22)
                        .SemiBold();

                    left.Item().Text("Purchase Invoice")
                        .FontSize(14);
                });

                row.RelativeItem().AlignRight().Column(right =>
                {
                    right.Item().Text(invoice.InvoiceNumber)
                        .FontSize(16)
                        .SemiBold();

                    right.Item().Text($"Date: {invoice.PurchaseDate:yyyy-MM-dd}");
                    right.Item().Text($"Status: {invoice.Status}");
                });
            });

            column.Item().PaddingTop(15).LineHorizontal(1);
        });
    }

    private static void ComposeContent(IContainer container, PurchaseInvoiceDetailDto invoice)
    {
        container.PaddingTop(20).Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(vendor =>
                {
                    vendor.Item().Text("Vendor")
                        .SemiBold()
                        .FontSize(12);

                    vendor.Item().Text(invoice.VendorName);
                    vendor.Item().Text(invoice.VendorEmail);
                });

                row.RelativeItem().Column(createdBy =>
                {
                    createdBy.Item().Text("Created By")
                        .SemiBold()
                        .FontSize(12);

                    createdBy.Item().Text(invoice.CreatedByName);
                    createdBy.Item().Text($"Created At: {invoice.CreatedAt:yyyy-MM-dd HH:mm}");
                });
            });

            column.Item()
                .PaddingVertical(20)
                .Element(table => ComposeItemsTable(table, invoice));

            column.Item().AlignRight().Text($"Total Amount: {invoice.TotalAmount:N2}")
                .FontSize(14)
                .SemiBold();

            column.Item()
                .PaddingTop(30)
                .Text("This invoice was generated by AutoCare IMS.")
                .FontSize(9)
                .FontColor(Colors.Grey.Darken1);
        });
    }

    private static void ComposeItemsTable(IContainer container, PurchaseInvoiceDetailDto invoice)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(35);
                columns.RelativeColumn(2);
                columns.RelativeColumn();
                columns.ConstantColumn(60);
                columns.ConstantColumn(90);
                columns.ConstantColumn(90);
            });

            table.Header(header =>
            {
                header.Cell().Element(HeaderCell).Text("#");
                header.Cell().Element(HeaderCell).Text("Part Name");
                header.Cell().Element(HeaderCell).Text("Part No.");
                header.Cell().Element(HeaderCell).AlignRight().Text("Qty");
                header.Cell().Element(HeaderCell).AlignRight().Text("Cost");
                header.Cell().Element(HeaderCell).AlignRight().Text("Line Total");
            });

            for (var i = 0; i < invoice.Items.Count; i++)
            {
                var item = invoice.Items[i];

                table.Cell().Element(BodyCell).Text((i + 1).ToString());
                table.Cell().Element(BodyCell).Text(item.PartName);
                table.Cell().Element(BodyCell).Text(item.PartNumber);
                table.Cell().Element(BodyCell).AlignRight().Text(item.Quantity.ToString());
                table.Cell().Element(BodyCell).AlignRight().Text(item.CostPricePerUnit.ToString("N2"));
                table.Cell().Element(BodyCell).AlignRight().Text(item.LineTotal.ToString("N2"));
            }
        });
    }

    private static IContainer HeaderCell(IContainer container)
    {
        return container
            .Background(Colors.Grey.Lighten2)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten1)
            .Padding(5);
    }

    private static IContainer BodyCell(IContainer container)
    {
        return container
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(5);
    }
}